# Generated by Django 4.1.5 on 2023-01-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_subida', models.DateField(auto_now=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('documento', models.ImageField(max_length=255, upload_to='pdf/')),
            ],
        ),
    ]
