# Generated by Django 4.1.5 on 2023-01-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
